berberim/urls.py
from django.urls import path, include
from berberproje import settings
from . import views, auth

urlpatterns = [
    path('', views.landing.as_view(), name='landing'),
    path('<province>/<district>-berberler', views.landing.as_view(), name='landing-with-province-n-district'),
    path('select-province-district', views.select_province_district, name='selectProvinceDistrict'),
    path('review_barbershop_ajax', views.review_barbershop_ajax, name='review-barbershop-ajax'), #AJAX CALL from landing-with-province-n-district page


    #customer
    path('barbershop-map', views.map, name='barbershop-map'),
    path('barbershop/<slug:barbershop_slug>', views.barbershop_view.as_view(), name='barbershop'),
    path('user-settings', views.user_settings_view.as_view(), name='user-settings'),
    path('load-districts', views.load_districts_ajax), #AJAX CALL from user-settings page

    #common
    path('barbershop/<slug:barbershop_slug>/profile', views.barbershop_profile.as_view(), name='barbershop-profile'),

    #for barbers
    path('user-settings/add-photo', views.userSettingsAddPhoto.as_view(), name='user-settings-add-photo'),



    #AUTH
    path('login', auth.login_view, name='login'),
    path('logout', auth.verify_logout, name='logout'),
    path('register', auth.register, name='register'),


]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

berberproje/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('berberim.urls')),
    path('api/', include('berberimapi.urls')),

]

berberim/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User, UserType, Barbershop, BarbershopEmployee, EMPLOYEE_TITLES_CHOICES,\
    SERVICE_NAME_CHOICES, Address, BarbershopService, Country, Province, District, BarbershopImage,\
    Service
from django.utils.translation import gettext as _
import re
from django.core.validators import RegexValidator
from django.contrib.auth import authenticate


alphanumeric = RegexValidator(r'^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.') 
#TODO make validators work, For example you can assign numeric values to employee names currently


class RegisterForm(UserCreationForm):

    username = forms.CharField(required = False, max_length = 30) #ignored
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'class': 'form-control form-control-lg border-left-0'})
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control form-control-lg border-left-0'})
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control form-control-lg border-left-0'})
    )
    user_type = forms.ModelChoiceField(
        queryset=UserType.objects.all().exclude(name='admin'),
        widget=forms.Select(
            attrs={'class': 'd-none'}
        ),
        initial=UserType.objects.get(name='customer')
    )

    class Meta:
	    model = User
	    fields = ["username", "email", "password1", "password2", "user_type"]
    
    
    def clean(self, *args, **kwargs):
        """
        Normal cleanup + username generation.
        """

        cleaned_data = super(UserCreationForm, self).clean(*args, **kwargs)
        if 'email' in cleaned_data:
            cleaned_data['username'] = cleaned_data['email']

        return cleaned_data
        

class LoginForm(forms.ModelForm):
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'class': 'form-control form-control-lg border-left-0'})
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control form-control-lg border-left-0'})
    )
    class Meta:
        model = User
        fields = ['email', 'password']

    def clean(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        user = authenticate(username=email, password=password)
        if not user: #TODO or not user.is_active
            raise forms.ValidationError("Sorry, that login was invalid. Please try again.")
        return self.cleaned_data

    def login(self, request):
        username = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        return user

class BarberUserSettingsForm(forms.Form):
    barbershop_id = forms.IntegerField(
        widget=forms.HiddenInput(),
        disabled=True,
        required=False #so we can create barbershop on first login
    )
    barbershop_name = forms.CharField(
        widget= forms.TextInput(
            attrs={
                'class':'form-control',
                'placeholder':'Aslan '+_('Barbershop')
            },
        ),
        label=_('What is the name of the shop?')
    )
    address_country = forms.ChoiceField(
        widget=forms.Select(
            attrs={
                'class':'init-select2 ml-1',
                'style':'width:32%;'
            }
        ),
        choices=[(c.country_code, c.country_name) for c in Country.objects.all()],
        initial=Country.objects.get(country_code="TR"),
        label=""
    )
    address_province = forms.ChoiceField(
        widget=forms.Select(
            attrs={
                'class':'init-select2',
                'style':'width:32%;'

            }
        ),
        choices=[(p.province_code, p.province_name) for p in Province.objects.all().order_by('province_code')],
        label=""
    )
    address_district = forms.ChoiceField(
        widget=forms.Select(
            attrs={
                'class':'init-select2',
                'style':'width:32%;'
            }
        ),
        choices=[(d.district_code, d.district_name) for d in District.objects.order_by('district_code')],
        label=""
    )
    address_description = forms.CharField(
        max_length=150,
        widget= forms.Textarea(
            attrs={
                'class':'form-control',
                'placeholder':'Mahalle/Cadde/Sokak, Bina/Daire No.',
                'rows':2
            }
        ),
        required=False,
        label=_('Address')
    )
    about = forms.CharField(
        max_length=1000,
        widget= forms.Textarea(
            attrs={
                'class':'form-control',
                'rows':5
            }
        ),
        required=False,
        label=_("Fill the 'about' section which would display in barbershop profile page")
    )
    address_lat = forms.DecimalField(
        decimal_places=6,
        widget=forms.HiddenInput(),
    )
    address_lng = forms.DecimalField(
        decimal_places=6,
        widget=forms.HiddenInput(),
    )

    def save(self, user):

        try:
            if self.cleaned_data['barbershop_id'] is None:
                raise(Barbershop.DoesNotExist)

            barbershop = Barbershop.objects.get(
                id=self.cleaned_data['barbershop_id'],
                owner=user
            )
            barbershop.name = self.cleaned_data['barbershop_name']
            barbershop.about = self.cleaned_data['about']
            barbershop.save()

            barbershop.address.country = Country.objects.get(country_code=self.cleaned_data['address_country'])
            barbershop.address.province = Province.objects.get(province_code=self.cleaned_data['address_province'])
            barbershop.address.district = District.objects.get(district_code=self.cleaned_data['address_district'])
            barbershop.address.description = self.cleaned_data['address_description'] if self.cleaned_data['address_description'].strip() else None
            barbershop.address.lat = self.cleaned_data['address_lat']
            barbershop.address.lng = self.cleaned_data['address_lng']
            barbershop.address.save()

            return barbershop
            
        except Barbershop.DoesNotExist as err:

            barbershop = Barbershop.objects.create(
                name=self.cleaned_data['barbershop_name'],
                owner=user,
            )

            for sevice_name in SERVICE_NAME_CHOICES:
                BarbershopService.objects.create(
                    name=sevice_name[0],
                    barbershop=barbershop
                )

            address = Address.objects.create(
                country = Country.objects.get(country_code=self.cleaned_data['address_country']),
                province = Province.objects.get(province_code=self.cleaned_data['address_province']),
                district = District.objects.get(district_code=self.cleaned_data['address_district']),
                description=self.cleaned_data['address_description'],
                lat=self.cleaned_data['address_lat'],
                lng=self.cleaned_data['address_lng'],
                created_by=user
            )
            barbershop.address = address
            barbershop.save()
            
            return barbershop

        # try: 
        #     b, b_created = Barbershop.objects.get_or_create(
        #         name=self.cleaned_data['barbershop_name'],
        #         owner=user
        #     )
        #     a, a_created = address_instance = Address.objects.get_or_create(
        #         description=self.cleaned_data['address_description'],
        #         created_by=user
        #     )
        #     b.address = a
        #     b.save()
        #     if b_created:
        #         for sevice_name in SERVICE_NAME_CHOICES:
        #             BarbershopServices.objects.create(
        #                 name=sevice_name[0],
        #                 barbershop=b
        #             )
        #     return b
        # except Exception as err:
        #     raise(err)


class EmployeeForm(forms.ModelForm):
    id = forms.IntegerField(
        widget= forms.NumberInput(attrs={'class':'d-none', 'readonly':'readonly'}),
        disabled=True,
        required=False #so we can create employee
    )

    name = forms.CharField(
        widget= forms.TextInput(
            attrs={
                'class':'form-control mb-2 mr-sm-2',
                'placeholder':_('Name'),
                'style':'width:35%',
            },
        ),
    )
    surname = forms.CharField(
        widget= forms.TextInput(
            attrs={
                'class':'form-control mb-2 mr-sm-2',
                'placeholder':_('Surname'),
                'style':'width:35%'
            },
        ),
    )
    title = forms.ChoiceField(
        widget=forms.Select(
            attrs={
                'class':'init-select2 mr-sm-2',
                'style':'width:25%;'
            }
        ),
        choices=EMPLOYEE_TITLES_CHOICES
    )
    class Meta:
        model = BarbershopEmployee
        fields = ['id', 'title', 'name', 'surname']

    def save(self, barbershop):
        try:
            if self.cleaned_data['id'] is None:
                raise(BarbershopEmployee.DoesNotExist)

            employee = BarbershopEmployee.objects.filter(
                id=self.cleaned_data['id'],
            ).update(**self.cleaned_data)

            return employee
        except BarbershopEmployee.DoesNotExist as err:

            employee = BarbershopEmployee.objects.create(
                name=self.cleaned_data['name'],
                surname=self.cleaned_data['surname'],
                title=self.cleaned_data['title'],
                barbershop=barbershop
            )

            return employee


class BarbershopServiceForm(forms.ModelForm):
    id = forms.IntegerField(

berberim/templates/customer/partials/filters.html
{% load static %}
{% load sass_tags %}
{% load i18n %}


<div class="container mt-5 {% if filters.filtered is False %} display-5 pt-5{% endif %}">
    <div class="row mb-2 justify-content-center text-center mb-3">
        <select name="address_province" class="init-select2 w-25 address-filter" id="id_address_province">
            {% for province in filters.provinces %}
                <option value="{{province.province_code}}"
                {% if filters.default_filtered_address.province_code == province.province_code %} selected="selected" {% endif %}>
                    {{province.province_name}}
                </option>
            {% endfor %}      
        </select>
        
        <select name="address_district" class="init-select2 w-25 address-filter" id="id_address_district">
            {% for district in filters.districts %}
                <option value="{{district.district_code}}"
                {% if filters.default_filtered_address.district_code == district.district_code %} selected="selected" {% endif %}
                    >{{district.district_name}}
                </option>
            {% endfor %}  
        </select>
    
    </div>
    <div class="row mb-2 justify-content-center mb-3">
        {% trans "Please select province and district that you are located." %}
    </div>
    <div class="row mb-2 justify-content-center">
        <form action="{% url 'selectProvinceDistrict' %}" method="post">
            {% csrf_token %}
            <input id="provinceInput" type="hidden" name="province_code" value="" />
            <input id="districtInput" type="hidden" name="district_code" value="" />
            <button type="submit" class="btn btn-primary">{% trans "Apply" %}</button>
        </form>
    </div>

</div>

berberim/templates/customer/partials/footer.html
{% load static %}
<footer class="footer">
    <div class="footer-wrap">
        <div class="w-100 clearfix">
        <span class="d-block text-center text-sm-left d-sm-inline-block">Copyright © 2019 <a href="https://www.templatewatch.com/" target="_blank">templatewatch</a>. All rights reserved.</span>
        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i class="mdi mdi-heart text-danger"></i></span>
        </div>
    </div>
</footer>

berberim/templates/customer/partials/layout.html
{% load static %}
{% load sass_tags %}
{% load i18n %}
<html>

    <head>
        <title>Berberim</title>

        <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"> -->
        <link rel="stylesheet" href="{% sass_src 'assets/kapella_bootstrap_theme/vendors/mdi/css/materialdesignicons.min.css' %}" type="text/css">
        <link rel="stylesheet" href="{% sass_src 'assets/kapella_bootstrap_theme/vendors/base/vendor.bundle.base.css' %}" type="text/css">
        <link rel="stylesheet" href="{% sass_src 'assets/kapella_bootstrap_theme/scss/style.scss' %}" type="text/css">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/rateYo/2.3.2/jquery.rateyo.min.css">
        <link rel="stylesheet" href="{% static 'css/shared.css' %}" type="text/css">

        <!-- <link rel="stylesheet" href="vendors/mdi/css/materialdesignicons.min.css"> -->

        <!-- 
        <link rel="stylesheet" href="{% static 'wololo/css/main.css' %}" type="text/css">
        <link rel="stylesheet" href="{% static 'wololo/css/game.css' %}" type="text/css">
        <link rel="stylesheet" href="{% static 'wololo/assets/css/animate.css' %}" type="text/css"> -->
        <!-- link(rel='shortcut icon', href='/favicon.png') -->
        <!-- <link rel="stylesheet" href="https://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css">
        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css"> 
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous"> -->


        {% block headcdn %} {% endblock %}
        <style>
            .content-wrapper{
            background-color: #b8c6db; background-image: linear-gradient(315deg, #b8c6db 0%, #f5f7fa 74%);}
        </style>


    </head>

    <body>
        <div class="container-scroller">
        {% include "customer/partials/navbar.html" %}
        <!-- <div class="popup">+1</div> -->
            
            <div class="container-fluid page-body-wrapper">
                <div class="main-panel">
                    <div class="content-wrapper">
                        {% block content %}
                        {% endblock %}
                    </div>
                    {% include 'customer/partials/footer.html' %}
                </div>
            </div>
        </div>




        <!-- <script type="text/javascript" src="{% static 'wololo/assets/js/popper.js/dist/umd/popper.min.js' %}"></script> -->
    
        <script type="text/javascript" src="{%static 'assets/kapella_bootstrap_theme/vendors/base/vendor.bundle.base.js' %}"></script>
        <script type="text/javascript" src="{%static 'assets/kapella_bootstrap_theme/js/template.js' %}"></script> 
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/js/select2.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/rateYo/2.3.2/jquery.rateyo.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>
        <!-- <script src="https://cdn.jsdelivr.net/npm/promise-polyfill"></script> -->
        <script type="text/javascript" src="{% static 'assets/blockUI/jquery.blockUI.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/main.js' %}"></script>

        <script>

        </script>
        {% block footerjs %}
        {% endblock %}

    </body>

</html>

berberim/templates/customer/partials/navbar.html
{% load static %}
{% load sass_tags %}
{% load i18n %}

<!-- partial:partials/_horizontal-navbar.html -->
<div class="horizontal-menu">
    <nav class="navbar top-navbar col-lg-12 col-12 p-0">
      <div class="container-fluid">
        <div class="navbar-menu-wrapper d-flex align-items-center justify-content-between">
          <ul class="navbar-nav navbar-nav-left">
            <li class="nav-item ml-0 mr-5 d-lg-flex d-none">
              <a href="#" class="nav-link horizontal-nav-left-menu"><i class="mdi mdi-format-list-bulleted"></i></a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link count-indicator dropdown-toggle d-flex align-items-center justify-content-center" id="notificationDropdown" href="#" data-toggle="dropdown">
                <i class="mdi mdi-bell mx-0"></i>
                <span class="count bg-success">2</span>
              </a>
              <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="notificationDropdown">
                <p class="mb-0 font-weight-normal float-left dropdown-header">Notifications</p>
                <a class="dropdown-item preview-item">
                  <div class="preview-thumbnail">
                      <div class="preview-icon bg-success">
                        <i class="mdi mdi-information mx-0"></i>
                      </div>
                  </div>
                  <div class="preview-item-content">
                      <h6 class="preview-subject font-weight-normal">Application Error</h6>
                      <p class="font-weight-light small-text mb-0 text-muted">
                        Just now
                      </p>
                  </div>
                </a>
                <a class="dropdown-item preview-item">
                  <div class="preview-thumbnail">
                      <div class="preview-icon bg-warning">
                        <i class="mdi mdi-settings mx-0"></i>
                      </div>
                  </div>
                  <div class="preview-item-content">
                      <h6 class="preview-subject font-weight-normal">Settings</h6>
                      <p class="font-weight-light small-text mb-0 text-muted">
                        Private message
                      </p>
                  </div>
                </a>
                <a class="dropdown-item preview-item">
                  <div class="preview-thumbnail">
                      <div class="preview-icon bg-info">
                        <i class="mdi mdi-account-box mx-0"></i>
                      </div>
                  </div>
                  <div class="preview-item-content">
                      <h6 class="preview-subject font-weight-normal">New user registration</h6>
                      <p class="font-weight-light small-text mb-0 text-muted">
                        2 days ago
                      </p>
                  </div>
                </a>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link count-indicator dropdown-toggle d-flex justify-content-center align-items-center" id="messageDropdown" href="#" data-toggle="dropdown">
                <i class="mdi mdi-email mx-0"></i>
                <span class="count bg-primary">4</span>
              </a>
              <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="messageDropdown">
                <p class="mb-0 font-weight-normal float-left dropdown-header">Messages</p>
                <a class="dropdown-item preview-item">
                  <div class="preview-thumbnail">
                      <img src="images/faces/face4.jpg" alt="image" class="profile-pic">
                  </div>
                  <div class="preview-item-content flex-grow">
                      <h6 class="preview-subject ellipsis font-weight-normal">David Grey
                      </h6>
                      <p class="font-weight-light small-text text-muted mb-0">
                        The meeting is cancelled
                      </p>
                  </div>
                </a>
                <a class="dropdown-item preview-item">
                  <div class="preview-thumbnail">
                      <img src="images/faces/face2.jpg" alt="image" class="profile-pic">
                  </div>
                  <div class="preview-item-content flex-grow">
                      <h6 class="preview-subject ellipsis font-weight-normal">Tim Cook
                      </h6>
                      <p class="font-weight-light small-text text-muted mb-0">
                        New product launch
                      </p>
                  </div>
                </a>
                <a class="dropdown-item preview-item">
                  <div class="preview-thumbnail">
                      <img src="images/faces/face3.jpg" alt="image" class="profile-pic">
                  </div>
                  <div class="preview-item-content flex-grow">
                      <h6 class="preview-subject ellipsis font-weight-normal"> {{user}}
                      </h6>
                      <p class="font-weight-light small-text text-muted mb-0">
                        Upcoming board meeting
                      </p>
                  </div>
                </a>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a href="#" class="nav-link count-indicator "><i class="mdi mdi-message-reply-text"></i></a>
            </li>
            <li class="nav-item nav-search d-none d-lg-block ml-3">
              <div class="input-group">
                  <div class="input-group-prepend">
                    <span class="input-group-text" id="search">
                      <i class="mdi mdi-magnify"></i>
                    </span>
                  </div>
                  <input type="text" class="form-control" placeholder="search" aria-label="search" aria-describedby="search">
              </div>
            </li>	
          </ul>
          <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
              <a class="navbar-brand brand-logo" href="index.html"><img src="{%static 'img/berberim.png' %}" alt="logo"/></a>
              <a class="navbar-brand brand-logo-mini" href="index.html"><img src="images/logo-mini.svg" alt="logo"/></a>
          </div>
          <ul class="navbar-nav navbar-nav-right">
              {% if user.is_anonymous %}
              <li class="nav-item dropdown d-lg-flex d-none">
                <a type="button" class="btn btn-inverse-primary btn-sm" href="{% url 'login' %}">{% trans "Login" %}</a>
              </li>
              <li class="nav-item dropdown d-lg-flex d-none">
                <a type="button" class="btn btn-inverse-primary btn-sm mr-3" href="{% url 'register' %}">{% trans "Register" %}</a>
              </li>
              {% else %}
              <!-- <li class="nav-item dropdown  d-lg-flex d-none">
                <button type="button" class="btn btn-inverse-primary btn-sm">Product </button>
              </li>
              <li class="nav-item dropdown d-lg-flex d-none">
                <a class="dropdown-toggle show-dropdown-arrow btn btn-inverse-primary btn-sm" id="nreportDropdown" href="#" data-toggle="dropdown">
                Reports
                </a>
                <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="nreportDropdown">
                    <p class="mb-0 font-weight-medium float-left dropdown-header">Reports</p>
                    <a class="dropdown-item">
                      <i class="mdi mdi-file-pdf text-primary"></i>
                      Pdf
                    </a>
                    <a class="dropdown-item">
                      <i class="mdi mdi-file-excel text-primary"></i>
                      Exel
                    </a>
                </div>
              </li> -->
              <li class="nav-item dropdown d-lg-flex d-none">
                <a type="button" class="btn btn-inverse-primary btn-sm" href="/user-settings">{% trans "Settings" %}</a>
              </li>
              <li class="nav-item nav-profile dropdown">
                <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="profileDropdown">
                  <span class="nav-profile-name">{{user.email}}</span>
                  <span class="online-status"></span>
                  <i class="mdi mdi-account text-dark"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
                    <a class="dropdown-item" href="/logout">
                      <i class="mdi mdi-logout text-primary"></i>
                      Logout
                    </a>
                </div>
              </li>
              {% endif %}
          </ul>
          <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="horizontal-menu-toggle">
            <span class="mdi mdi-menu"></span>
          </button>
        </div>
      </div>
    </nav>
    <nav class="bottom-navbar">
      <div class="container">
          <ul class="nav page-navigation">
            <li class="nav-item d-hidden"></li>

            <li class="nav-item {% if request.resolver_match.url_name == 'landing' %}active{% endif %}">
              <a class="nav-link p-3" href="/">
                <i class="mdi mdi-file-document-box menu-icon"></i>
                <span class="menu-title">{% trans "Barbershops" %}</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link p-3 {% if request.resolver_match.url_name == 'user-settings' %}active{% endif %}" href="/barbershop-map">
                <i class="mdi mdi-map menu-icon"></i>
                <span class="menu-title">{% trans "Barbershop Map" %}</span>
              </a>
            </li>
            <li class="nav-item d-hidden"></li>

            <!-- <li class="nav-item {% if request.resolver_match.url_name == 'visited-barbershops' %}active{% endif %}">
              <a class="nav-link p-3" href="/">
                <i class="mdi mdi-file-document-box menu-icon"></i>
                <span class="menu-title">Visited Barbershops</span>
              </a>
            </li> -->
          </ul>
      </div>
    </nav>
  </div>