berberim/urls.py
from django.urls import path, include
from berberproje import settings
from . import views, auth

urlpatterns = [
    path('', views.landing.as_view(), name='landing'),
    path('<province>/<district>-berberler', views.landing.as_view(), name='landing-with-province-n-district'),
    path('select-province-district', views.select_province_district, name='selectProvinceDistrict'),
    path('review_barbershop_ajax', views.review_barbershop_ajax, name='review-barbershop-ajax'), #AJAX CALL from landing-with-province-n-district page


    #customer
    path('barbershop-map', views.map, name='barbershop-map'),
    path('barbershop/<slug:barbershop_slug>', views.barbershop_view.as_view(), name='barbershop'),
    path('user-settings', views.user_settings_view.as_view(), name='user-settings'),
    path('load-districts', views.load_districts_ajax), #AJAX CALL from user-settings page

    #common
    path('barbershop/<slug:barbershop_slug>/profile', views.barbershop_profile.as_view(), name='barbershop-profile'),

    #for barbers
    path('user-settings/add-photo', views.userSettingsAddPhoto.as_view(), name='user-settings-add-photo'),



    #AUTH
    path('login', auth.login_view, name='login'),
    path('logout', auth.verify_logout, name='logout'),
    path('register', auth.register, name='register'),


]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

berberproje/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('berberim.urls')),
    path('api/', include('berberimapi.urls')),

]

berberim/models.py
from django.urls import reverse
from django_extensions.db.fields import AutoSlugField
from django.contrib.postgres.fields import JSONField, ArrayField
from django.db.models import AutoField
from django.db.models import BooleanField
from django.db.models import CharField
from django.db.models import DateTimeField
from django.db.models import EmailField
from django.db.models import IntegerField
from django.db.models import PositiveIntegerField
from django.db.models import SmallIntegerField
from django.db.models import TextField
from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth import get_user_model
from django.contrib.auth import models as auth_models
from django.db import models as models
from django_extensions.db import fields as extension_fields
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.utils.translation import gettext as _
from django.utils import timezone
from django.core.validators import MaxValueValidator, MinValueValidator

class UserManager(BaseUserManager):
    """
    Custom user model manager where email is the unique identifiers
    for authentication instead of usernames.
    """
    def create_user(self, email, password, user_type_id, **extra_fields):
        """
        Create and save a User with the given email and password.
        """
        if not email:
            raise ValueError(_('The Email must be set'))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.user_type =UserType.objects.get(id=user_type_id) 
        user.save()
        return user

    def create_superuser(self, email, password, user_type_id, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))
        return self.create_user(email, password, user_type_id, **extra_fields)

class User(AbstractUser):

    # Fields
    id = models.AutoField(primary_key=True)
    email = models.EmailField(unique=True)
    created = models.DateTimeField(auto_now_add=True, editable=False)

    # Relationship Fields
    user_type = models.ForeignKey(
        'berberim.UserType',
        on_delete=models.CASCADE, related_name="users",
    )

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['user_type_id', 'username']

    objects = UserManager()

    class Meta:
        ordering = ('-pk',)

    def __str__(self):
        return self.email

    def __unicode__(self):
        return u'%s' % self.pk

    def get_absolute_url(self):
        return reverse('berberim_user_detail', args=(self.slug,))

    def get_update_url(self):
        return reverse('berberim_user_update', args=(self.slug,))
    
    def number_of_unreviewed_past_schedules(self):
        unreviewed_schedules = self.barbershop_schedules.filter(end_time__lte=timezone.localtime(), reviewed=False)
        return unreviewed_schedules.count()

    @property
    def past_barbershop_schedules(self):
        return self.barbershop_schedules.filter(end_time__lte=timezone.localtime()).all()

class UserType(models.Model):

    # Fields
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=20, unique=True)

    class Meta:
        ordering = ('-pk',)

    def __str__(self):
        return self.name

    def __unicode__(self):
        return u'%s' % self.pk

    def get_absolute_url(self):
        return reverse('berberim_usertype_detail', args=(self.pk,))


    def get_update_url(self):
        return reverse('berberim_usertype_update', args=(self.pk,))


class Barbershop(models.Model):

    # Fields
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    slug = extension_fields.AutoSlugField(unique=True, populate_from='name', blank=True)
    created = models.DateTimeField(auto_now_add=True, editable=False)
    review_rate = models.FloatField(
        validators=[
            MaxValueValidator(10),
            MinValueValidator(0),
        ],
        default=0
    )
    about = models.CharField(max_length=1000, null=True)
    # Relationship Fields
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE, related_name="barbershops", 
    )
    address = models.OneToOneField(
       'berberim.Address',
        on_delete=models.CASCADE, related_name="barbershops_2", null=True, blank=True
    )

    @property
    def active_services(self):
        return [brb_srv.service for brb_srv in self.services.all()]


    def set_new_review_rate(self, incoming_rate):
        crc = self.customer_reviews.count()
        if crc == 0: crc = 1
        new_review_rate = (float(self.review_rate * crc) + incoming_rate) / float(crc + 1)
        self.review_rate = new_review_rate
        self.save()

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.name

    def __unicode__(self):
        return u'%s' % self.slug

    def get_absolute_url(self):
        return reverse('berberim_barbershop_detail', args=(self.slug,))


    def get_update_url(self):
        return reverse('berberim_barbershop_update', args=(self.slug,))

#Expand this array by customer demand
EMPLOYEE_TITLES_CHOICES = [
    ('Master', _('Master')),
    ('Journeyman', _('Journeyman')),
    ('Apprentice', _('Apprentice')),
]

class BarbershopEmployee(models.Model):

    # Fields
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=30)
    surname = models.CharField(max_length=30)
    title = models.CharField(max_length=30, choices=EMPLOYEE_TITLES_CHOICES)
    created = models.DateTimeField(auto_now_add=True, editable=False)

    # Relationship Fields
    barbershop = models.ForeignKey(
        'berberim.Barbershop',
        on_delete=models.CASCADE, related_name="employees", 
    )

    @property
    def full_name(self):
        return self.name.title() + ' ' + self.surname.title()

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.full_name

    def __unicode__(self):
        return u'%s' % self.pk

    def get_absolute_url(self):
        return reverse('berberim_barbershopemployee_detail', args=(self.pk,))


    def get_update_url(self):
        return reverse('berberim_barbershopemployee_update', args=(self.pk,))


#Expand this array by customer demand
SERVICE_NAME_CHOICES = [
    ('Haircut', _('Haircut')),
    ('Beardcut', _('Beardcut')),
    ('Hair Wash', _('Hair Wash')),
]

class Service(models.Model):

    # Fields
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=30)
    created = models.DateTimeField(auto_now_add=True, editable=False)

    def __str__(self):
        return self.name

    def __unicode__(self):
        return u'%s' % self.pk

    def get_absolute_url(self):
        return reverse('berberim_service_detail', args=(self.pk,))


    def get_update_url(self):
        return reverse('berberim_service_update', args=(self.pk,))


class BarbershopService(models.Model):

    # Fields
    id = models.AutoField(primary_key=True)
    price = models.PositiveIntegerField(default=10)
    duration_mins = models.PositiveSmallIntegerField(default=20)
    created = models.DateTimeField(auto_now_add=True, editable=False)

    # Relationship Fields
    barbershop = models.ForeignKey(
        'berberim.Barbershop',
        on_delete=models.CASCADE, related_name="services", 
    )
    service = models.ForeignKey(
        'berberim.Service',
        on_delete=models.CASCADE 
    )

    class Meta:
        ordering = ('-created',)

    def __unicode__(self):
        return u'%s' % self.pk

    def get_absolute_url(self):
        return reverse('berberim_barbershopservice_detail', args=(self.pk,))


    def get_update_url(self):
        return reverse('berberim_barbershopservice_update', args=(self.pk,))

        
class Address(models.Model):

    # Fields
    id = models.AutoField(primary_key=True)
    # province = models.CharField(max_length=30, choices=TR_PROVINCES)
    # city = models.CharField(max_length=30, choices=TR_CITIES)
    description = models.CharField(max_length=255)
    lng = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    lat = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)

    # Relationship Fields
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE, related_name="addressess", 
    )
    country = models.ForeignKey(
        'berberim.Country',
        on_delete=models.CASCADE, related_name="addresss", 
    )
    province = models.ForeignKey(
        'berberim.Province',
        on_delete=models.CASCADE, related_name="addresss", 
    )
    district = models.ForeignKey(
        'berberim.District',
        on_delete=models.CASCADE, related_name="addresss", 
    )

    class Meta:
        ordering = ('-pk',)

    def __unicode__(self):
        return u'%s' % self.pk

    def get_absolute_url(self):
        return reverse('berberim_addresses_detail', args=(self.pk,))


    def get_update_url(self):
        return reverse('berberim_addresses_update', args=(self.pk,))


class Country(models.Model):

    # Fields
    country_code = models.CharField(primary_key=True, max_length=3)
    country_name = models.CharField(max_length=30)


    class Meta:
        ordering = ('-pk',)

    def __str__(self):
        return self.country_name

    def __unicode__(self):

berberim/templates/login.html
{% load static %}
{% load sass_tags %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">

    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Kapella Bootstrap Admin Dashboard Template</title>
        <!-- base:css -->
        <link rel="stylesheet" href="{% sass_src 'assets/kapella_bootstrap_theme/vendors/mdi/css/materialdesignicons.min.css' %}" type="text/css">
        <link rel="stylesheet" href="{% sass_src 'assets/kapella_bootstrap_theme/vendors/base/vendor.bundle.base.css' %}" type="text/css">
        <link rel="stylesheet" href="{% sass_src 'assets/kapella_bootstrap_theme/scss/style.scss' %}" type="text/css">
        <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
    </head>

    <body>
    <div class="container-scroller">
        <div class="container-fluid page-body-wrapper full-page-wrapper">
        <div class="content-wrapper d-flex align-items-stretch auth auth-img-bg">
            <div class="row flex-grow">
            <div class="col-lg-6 d-flex align-items-center justify-content-center">
                <div class="auth-form-transparent text-left p-3">
                <div class="brand-logo">
                    <img src="{%static 'img/berberim.png' %}" alt="logo"/>
                </div>
                <!-- 
                <h4>Welcome back!</h4>
                <h6 class="font-weight-light">Happy to see you again!</h6> -->
                <form id="login-form" class="pt-3" action="{% url 'login' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                    <label for="exampleInputEmail">{% trans "Email" %}</label>
                    <div class="input-group">
                        <div class="input-group-prepend bg-transparent">
                        <span class="input-group-text bg-transparent border-right-0">
                            <i class="mdi mdi-account-outline text-primary"></i>
                        </span>
                        </div>
                        <!-- <input type="text" class="form-control form-control-lg border-left-0" id="exampleInputEmail" placeholder="Username"> -->
                        {{form.email}}
                    </div>
                    <div class="text-danger">
                        {{form.email.errors}}
                    </div>
                    </div>
                    <div class="form-group">
                    <label for="exampleInputPassword">{% trans "Password" %}</label>
                    <div class="input-group">
                        <div class="input-group-prepend bg-transparent">
                        <span class="input-group-text bg-transparent border-right-0">
                            <i class="mdi mdi-lock-outline text-primary"></i>
                        </span>
                        </div>
                        <!-- <input type="password" class="form-control form-control-lg border-left-0" id="exampleInputPassword" placeholder="Password">    -->
                        {{form.password}}     
                    </div>
                    <div class="text-danger">
                        {{form.password.errors}}
                    </div>                
                    </div>
                    <div class="my-2 d-flex justify-content-between align-items-center">
                        <!-- <div class="form-check">
                            <label class="form-check-label text-muted">
                            <input type="checkbox" class="form-check-input">
                            Keep me signed in
                            </label>
                        </div> -->
                        <a href="#" class="auth-link text-black">{% trans "Forgot password?" %}</a>
                    </div>
                    {% if form.non_field_errors %}
                    <ul class='form-errors'>
                        {% for error in form.non_field_errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                    <div class="my-3">
                        <a id="submit-btn" class="btn btn-block btn-primary btn-lg font-weight-medium auth-form-btn" href="#">{% trans "LOGIN" %}</a>
                    </div>
                    <div class="mb-2 d-flex">
                    <button type="button" class="btn btn-facebook auth-form-btn flex-grow mr-1">
                        <i class="mdi mdi-facebook mr-2"></i>Facebook
                    </button>
                    <button type="button" class="btn btn-google auth-form-btn flex-grow ml-1">
                        <i class="mdi mdi-google mr-2"></i>Google
                    </button>
                    </div>
                    <div class="text-center mt-4 font-weight-light">
                    {% trans "Don't have an account?" %} <a href="/register" class="text-primary">{% trans "Create Account" %}</a>
                    </div>
                </form>
                </div>
            </div>
            <div class="col-lg-6 login-half-bg d-flex flex-row">
                <p class="text-white font-weight-medium text-center flex-grow align-self-end">Copyright &copy; 2019  All rights reserved.</p>
            </div>
            </div>
        </div>
        <!-- content-wrapper ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- base:js -->
    <script type="text/javascript" src="{%static 'assets/kapella_bootstrap_theme/vendors/base/vendor.bundle.base.js' %}"></script>
    <script type="text/javascript" src="{%static 'assets/kapella_bootstrap_theme/js/template.js' %}"></script>
    <!-- endinject -->
    <!-- plugin js for this page -->
    <!-- End plugin js for this page -->
    <!-- Custom js for this page-->
    <!-- End custom js for this page-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
    <script>
        $(function(){
            const form = $("#login-form")
            $("#submit-btn").on("click", function(){
                form.submit()
            })
        })
    </script>

    </body>
</html>

berberim/templates/register.html
{% load static %}
{% load sass_tags %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">

    <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Kapella Bootstrap Admin Dashboard Template</title>
  
    <link rel="stylesheet" href="{% sass_src 'assets/kapella_bootstrap_theme/vendors/mdi/css/materialdesignicons.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% sass_src 'assets/kapella_bootstrap_theme/vendors/base/vendor.bundle.base.css' %}" type="text/css">
    <link rel="stylesheet" href="{% sass_src 'assets/kapella_bootstrap_theme/scss/style.scss' %}" type="text/css">
    <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">

    </head>

    <body>
    <div class="container-scroller">
        <div class="container-fluid page-body-wrapper full-page-wrapper">
        <div class="content-wrapper d-flex align-items-stretch auth auth-img-bg">
            <div class="row flex-grow">
                <div class="col-lg-6 d-flex align-items-center justify-content-center">
                    <div class="auth-form-transparent text-left p-3">
                        <div class="brand-logo">
                            <img src="{%static 'img/berberim.png' %}" alt="logo"/>
                        </div>
                        <h4>{% trans "Join us today!" %}</h4>
                        <h6 class="font-weight-light">{% trans "Register as customer or barber." %}</h6>
                        <form id="register-form" class="pt-3" action="{% url 'register' %}" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                {{form.user_type}}
                                <input type="checkbox" id="userTypeSwitch" data-toggle="toggle"
                                data-on="Müşteri<br>Kayıt" data-off="Berber<br>Kayıt" data-onstyle="info" 
                                data-offstyle="warning" checked="" required="">
                                <div class="text-danger">
                                    {{form.user_type.errors}}
                                </div>
                            </div>
                            <div class="form-group">
                                <label>{% trans "Email" %}</label>
                                <div class="input-group">
                                    <div class="input-group-prepend bg-transparent">
                                        <span class="input-group-text bg-transparent border-right-0">
                                            <i class="mdi mdi-email-outline text-primary"></i>
                                        </span>
                                    </div>
                                    <!-- <input type="email" class="form-control form-control-lg border-left-0" name="inputEmail" placeholder="Email"> -->
                                    {{form.email}}
                                </div>
                                <div class="text-danger">
                                    {{form.email.errors}}
                                </div>
                            </div>
                            <div class="form-group">
                                <label>{% trans "Password" %}</label>
                                <div class="input-group">
                                    <div class="input-group-prepend bg-transparent">
                                        <span class="input-group-text bg-transparent border-right-0">
                                            <i class="mdi mdi-lock-outline text-primary"></i>
                                        </span>
                                    </div>
                                    <!-- <input type="password" class="form-control form-control-lg border-left-0" name="inputPassword" placeholder="Password">                         -->
                                    {{form.password1}}
                                </div>
                                <div class="text-danger">
                                    {{form.password1.errors}}
                                </div>                     
                            </div>
                            <div class="form-group">
                                <label>{% trans "Repeat Password" %}</label>
                                <div class="input-group">
                                    <div class="input-group-prepend bg-transparent">
                                        <span class="input-group-text bg-transparent border-right-0">
                                            <i class="mdi mdi-lock-outline text-primary"></i>
                                        </span>
                                    </div>
                                    <!-- <input type="password" class="form-control form-control-lg border-left-0" name="inputPassword" placeholder="Password">                         -->
                                    {{form.password2}}
                                </div>
                                <div class="text-danger">
                                    {{form.password2.errors}}
                                </div>                        
                            </div>
                            <div class="mt-3">
                                <a id="submit-btn" class="btn btn-block btn-primary btn-lg font-weight-medium auth-form-btn" href="#">{% trans "SIGN UP" %}</a>
                            </div>
                            <div class="mt-3">
                                <h6 class="font-weight-light">
                                    {% trans "By cliciking Sign Up, you agree to our Terms & Privacy Policy." %}
                                </h6>
                            </div>
                            <div class="text-center mt-4 font-weight-light">
                                {% trans "Already have an account?" %} <a href="/login" class="text-primary">{% trans "Login" %}</a>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-lg-6 register-half-bg d-flex flex-row">
                    <p class="text-white font-weight-medium text-center flex-grow align-self-end">Copyright &copy; 2019  All rights reserved.</p>
                </div>
            </div>
        </div>
        <!-- content-wrapper ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- base:js -->
    <script type="text/javascript" src="{%static 'assets/kapella_bootstrap_theme/vendors/base/vendor.bundle.base.js' %}"></script>
    <script type="text/javascript" src="{%static 'assets/kapella_bootstrap_theme/js/template.js' %}"></script>

    <!-- endinject -->
    <!-- Plugin js for this page-->
    <!-- End plugin js for this page-->
    <!-- inject:js -->
    <!-- endinject -->
    <!-- plugin js for this page -->
    <!-- End plugin js for this page -->
    <!-- Custom js for this page-->
    <!-- End custom js for this page-->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
    <script>
        $(function(){
            let form = $("#register-form")
            $("#submit-btn").on("click", function(){
                form.submit()
            })
            const userTypeSwitch = $("#userTypeSwitch").bootstrapToggle()
                .on("change",function(){
                    let state = $(this).prop('checked')
                    console.log(state)
                    switch(state){
                        case true: 
                            $("#id_user_type").val("{{data.customer_usertype_pk}}") //customer.pk
                            break
                        case false:
                            $("#id_user_type").val("{{data.barber_usertype_pk}}") //barber.pk
                            break 
                    }
                })
            $(document).keypress(function (e) {
                if (e.which == 13) { //enter key
                    $('#submit-btn').trigger('click');
                }
            });
        })
    </script>
    </body>

</html>